# Data Cleaning with Python

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r"C:\Users\a\Downloads\Nashville Housing Data for Data Cleaning (2).xlsx")

In [3]:
df

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,30469,188 10 0A 101.00,SINGLE FAMILY,"1435 WINDING CREEK DR, NOLENSVILLE",2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56473,27707,188 10 0A 107.00,SINGLE FAMILY,"1423 WINDING CREEK DR, NOLENSVILLE",2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56474,52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,"1804 GRACE POINT LN, NOLENSVILLE",2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56475,54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,"1709 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56476,54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,"1713 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Drop Duplicates

In [4]:
df.drop_duplicates()

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,30469,188 10 0A 101.00,SINGLE FAMILY,"1435 WINDING CREEK DR, NOLENSVILLE",2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56473,27707,188 10 0A 107.00,SINGLE FAMILY,"1423 WINDING CREEK DR, NOLENSVILLE",2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56474,52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,"1804 GRACE POINT LN, NOLENSVILLE",2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56475,54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,"1709 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56476,54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,"1713 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Drop NaN Values

In [10]:
df.dropna(inplace = True)

# Description of Data

In [11]:
df.describe()

,UniqueID,SalePrice,Acreage,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
count,23705.000000,2.370500e+04,23705.000000,2.370500e+04,2.370500e+04,2.370500e+04,23705.000000,23705.000000,23705.000000,23705.000000
mean,27584.465260,2.750023e+05,0.455836,6.904970e+04,1.730583e+05,2.447819e+05,1963.723139,3.094115,1.896984,0.286648
std,16549.621489,3.044420e+05,0.793932,1.021612e+05,1.935828e+05,2.723682e+05,26.385627,0.850667,0.955172,0.489565
min,1.000000,1.000000e+02,0.040000,1.000000e+02,1.400000e+03,1.260000e+04,1799.000000,0.000000,0.000000,0.000000
25%,13068.000000,1.250000e+05,0.190000,2.200000e+04,8.390000e+04,1.098000e+05,1948.000000,3.000000,1.000000,0.000000
50%,27214.000000,1.850000e+05,0.270000,2.990000e+04,1.176000e+05,1.548000e+05,1960.000000,3.000000,2.000000,0.000000
75%,42016.000000,3.249000e+05,0.450000,6.030000e+04,1.892000e+05,2.782000e+05,1983.000000,4.000000,2.000000,1.000000
max,56615.000000,1.075000e+07,47.500000,1.869000e+06,5.824300e+06,6.402600e+06,2017.000000,11.000000,10.000000,3.000000

# Expanding PropertyAddress

In [12]:
df['PropertyAddress']

0        1808  FOX CHASE DR, GOODLETTSVILLE
1        1832  FOX CHASE DR, GOODLETTSVILLE
2        1864 FOX CHASE  DR, GOODLETTSVILLE
3        1853  FOX CHASE DR, GOODLETTSVILLE
4        1829  FOX CHASE DR, GOODLETTSVILLE
                        ...
54210              6640 HOLT  RD, NASHVILLE
54211              6608  HOLT RD, NASHVILLE
54212              6635  HOLT RD, NASHVILLE
54213           6552  REDMOND LN, NASHVILLE
54214         105  HOLT HILLS RD, NASHVILLE
Name: PropertyAddress, Length: 23705, dtype: object

In [13]:
df[['Street', 'City']] = df['PropertyAddress'].str.split(',', expand = True)

In [14]:
df

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,...,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,Street,City
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",...,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0,1808 FOX CHASE DR,GOODLETTSVILLE
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",...,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0,1832 FOX CHASE DR,GOODLETTSVILLE
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",...,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0,1864 FOX CHASE DR,GOODLETTSVILLE
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",...,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0,1853 FOX CHASE DR,GOODLETTSVILLE
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",...,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0,1829 FOX CHASE DR,GOODLETTSVILLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54210,51558,180 00 0 081.00,SINGLE FAMILY,"6640 HOLT RD, NASHVILLE",2016-07-08,258000,20160712-0071418,No,"CAHILL, DAVID W. II & MORYN","6640 HOLT RD, NASHVILLE, TN",...,GENERAL SERVICES DISTRICT,111000.0,155800.0,268000.0,1978.0,4.0,2.0,0.0,6640 HOLT RD,NASHVILLE
54211,34115,180 00 0 085.00,SINGLE FAMILY,"6608 HOLT RD, NASHVILLE",2015-07-27,339528,20150804-0077423,No,"MISRA, SANJEEV & YABKO, STACEY","6608 HOLT RD, NASHVILLE, TN",...,GENERAL SERVICES DISTRICT,111000.0,141700.0,252700.0,1978.0,3.0,2.0,0.0,6608 HOLT RD,NASHVILLE
54212,20731,180 00 0 094.00,SINGLE FAMILY,"6635 HOLT RD, NASHVILLE",2014-09-05,230000,20140905-0081621,No,"RALSTON, MARY DEE, IRREVOCABLE TRUST","6635 HOLT RD, NASHVILLE, TN",...,GENERAL SERVICES DISTRICT,111500.0,210400.0,321900.0,1980.0,3.0,2.0,0.0,6635 HOLT RD,NASHVILLE
54213,23447,180 00 0 114.00,SINGLE FAMILY,"6552 REDMOND LN, NASHVILLE",2014-11-24,237900,20141125-0108837,No,"MARTIN, KARA F. & SETH","6552 REDMOND LN, NASHVILLE, TN",...,GENERAL SERVICES DISTRICT,59000.0,104100.0,163100.0,1985.0,3.0,3.0,0.0,6552 REDMOND LN,NASHVILLE
54214,23448,180 00 0 230.00,SINGLE FAMILY,"105 HOLT HILLS RD, NASHVILLE",2014-11-12,259000,20141203-0110910,No,"AKERS, DOUGLAS P. & MELISSA W.","105 HOLT HILLS RD, NASHVILLE, TN",...,GENERAL SERVICES DISTRICT,59000.0,194000.0,253000.0,2001.0,3.0,2.0,1.0,105 HOLT HILLS RD,NASHVILLE

# Put all the prices in dollars

In [15]:
df.head(2)

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,...,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,Street,City
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",...,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0,1808 FOX CHASE DR,GOODLETTSVILLE
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",...,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0,1832 FOX CHASE DR,GOODLETTSVILLE

In [16]:
df['SalePrice'] = df['SalePrice'].astype('float')

In [17]:
# col_to_add = [df.iloc[:, 5], df.iloc[:, 12], df.iloc[:, 13], df.iloc[:, 14]]

salesprice = np.array(df['SalePrice'].values)
landvalue = np.array(df['LandValue'].values)
buildingvalue = np.array(df['BuildingValue'].values)
totalvalue = np.array(df['TotalValue'].values)

formatted_sales = [f'${num:,.2f}' for num in salesprice]
formatted_land = [f'${num:,.2f}' for num in landvalue]
formatted_building = [f'${num:,.2f}' for num in buildingvalue]
formatted_total = [f'${num:,.2f}' for num in totalvalue]

In [18]:
#do this for the rest
df['TotalValue'] = formatted_total
df['SalePrice'] = formatted_sales
df['BuildingValue'] = formatted_building
df['LandValue'] = formatted_sales

# Split OwnerAddress

In [19]:
df['OwnerAddress'].head(5)

0    1808  FOX CHASE DR, GOODLETTSVILLE, TN
1    1832  FOX CHASE DR, GOODLETTSVILLE, TN
2    1864  FOX CHASE DR, GOODLETTSVILLE, TN
3    1853  FOX CHASE DR, GOODLETTSVILLE, TN
4    1829  FOX CHASE DR, GOODLETTSVILLE, TN
Name: OwnerAddress, dtype: object

In [20]:
df[['OwnerStreet', 'OwnerCity', 'State']] = df['OwnerAddress'].str.split(',', expand = True)

In [21]:
df.head(2)

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,...,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,Street,City,OwnerStreet,OwnerCity,State
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,"$240,000.00",20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",...,"$235,700.00",1986.0,3.0,3.0,0.0,1808 FOX CHASE DR,GOODLETTSVILLE,1808 FOX CHASE DR,GOODLETTSVILLE,TN
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,"$366,000.00",20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",...,"$319,000.00",1998.0,3.0,3.0,2.0,1832 FOX CHASE DR,GOODLETTSVILLE,1832 FOX CHASE DR,GOODLETTSVILLE,TN

# Change Yearbuilt, Bedrooms, Fullbath and Halfbath to integers

In [22]:
df

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,...,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,Street,City,OwnerStreet,OwnerCity,State
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,"$240,000.00",20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",...,"$235,700.00",1986.0,3.0,3.0,0.0,1808 FOX CHASE DR,GOODLETTSVILLE,1808 FOX CHASE DR,GOODLETTSVILLE,TN
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,"$366,000.00",20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",...,"$319,000.00",1998.0,3.0,3.0,2.0,1832 FOX CHASE DR,GOODLETTSVILLE,1832 FOX CHASE DR,GOODLETTSVILLE,TN
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,"$435,000.00",20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",...,"$298,000.00",1987.0,4.0,3.0,0.0,1864 FOX CHASE DR,GOODLETTSVILLE,1864 FOX CHASE DR,GOODLETTSVILLE,TN
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,"$255,000.00",20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",...,"$197,300.00",1985.0,3.0,3.0,0.0,1853 FOX CHASE DR,GOODLETTSVILLE,1853 FOX CHASE DR,GOODLETTSVILLE,TN
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,"$278,000.00",20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",...,"$202,300.00",1984.0,4.0,3.0,0.0,1829 FOX CHASE DR,GOODLETTSVILLE,1829 FOX CHASE DR,GOODLETTSVILLE,TN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54210,51558,180 00 0 081.00,SINGLE FAMILY,"6640 HOLT RD, NASHVILLE",2016-07-08,"$258,000.00",20160712-0071418,No,"CAHILL, DAVID W. II & MORYN","6640 HOLT RD, NASHVILLE, TN",...,"$268,000.00",1978.0,4.0,2.0,0.0,6640 HOLT RD,NASHVILLE,6640 HOLT RD,NASHVILLE,TN
54211,34115,180 00 0 085.00,SINGLE FAMILY,"6608 HOLT RD, NASHVILLE",2015-07-27,"$339,528.00",20150804-0077423,No,"MISRA, SANJEEV & YABKO, STACEY","6608 HOLT RD, NASHVILLE, TN",...,"$252,700.00",1978.0,3.0,2.0,0.0,6608 HOLT RD,NASHVILLE,6608 HOLT RD,NASHVILLE,TN
54212,20731,180 00 0 094.00,SINGLE FAMILY,"6635 HOLT RD, NASHVILLE",2014-09-05,"$230,000.00",20140905-0081621,No,"RALSTON, MARY DEE, IRREVOCABLE TRUST","6635 HOLT RD, NASHVILLE, TN",...,"$321,900.00",1980.0,3.0,2.0,0.0,6635 HOLT RD,NASHVILLE,6635 HOLT RD,NASHVILLE,TN
54213,23447,180 00 0 114.00,SINGLE FAMILY,"6552 REDMOND LN, NASHVILLE",2014-11-24,"$237,900.00",20141125-0108837,No,"MARTIN, KARA F. & SETH","6552 REDMOND LN, NASHVILLE, TN",...,"$163,100.00",1985.0,3.0,3.0,0.0,6552 REDMOND LN,NASHVILLE,6552 REDMOND LN,NASHVILLE,TN
54214,23448,180 00 0 230.00,SINGLE FAMILY,"105 HOLT HILLS RD, NASHVILLE",2014-11-12,"$259,000.00",20141203-0110910,No,"AKERS, DOUGLAS P. & MELISSA W.","105 HOLT HILLS RD, NASHVILLE, TN",...,"$253,000.00",2001.0,3.0,2.0,1.0,105 HOLT HILLS RD,NASHVILLE,105 HOLT HILLS RD,NASHVILLE,TN

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23705 entries, 0 to 54214
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UniqueID         23705 non-null  int64
 1   ParcelID         23705 non-null  object
 2   LandUse          23705 non-null  object
 3   PropertyAddress  23705 non-null  object
 4   SaleDate         23705 non-null  datetime64[ns]
 5   SalePrice        23705 non-null  object
 6   LegalReference   23705 non-null  object
 7   SoldAsVacant     23705 non-null  object
 8   OwnerName        23705 non-null  object
 9   OwnerAddress     23705 non-null  object
 10  Acreage          23705 non-null  float64
 11  TaxDistrict      23705 non-null  object
 12  LandValue        23705 non-null  object
 13  BuildingValue    23705 non-null  object
 14  TotalValue       23705 non-null  object
 15  YearBuilt        23705 non-null  float64
 16  Bedrooms         23705 non-null  float64
 17  FullBath         23705 non-null  float64
 18  HalfBath         23705 non-null  float64
 19  Street           23705 non-null  object
 20  City             23705 non-null  object
 21  OwnerStreet      23705 non-null  object
 22  OwnerCity        23705 non-null  object
 23  State            23705 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(1), object(17)
memory usage: 4.5+ MB

In [24]:
year = np.array(df['YearBuilt'], np.int64)
rooms = np.array(df['Bedrooms'], np.int64)
full = np.array(df['FullBath'], np.int64)
half = np.array(df['HalfBath'], np.int64)

df['YearBuilt'] = year
df['Bedrooms'] = rooms
df['FullBath'] = full
df['HalfBath'] = half

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23705 entries, 0 to 54214
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UniqueID         23705 non-null  int64
 1   ParcelID         23705 non-null  object
 2   LandUse          23705 non-null  object
 3   PropertyAddress  23705 non-null  object
 4   SaleDate         23705 non-null  datetime64[ns]
 5   SalePrice        23705 non-null  object
 6   LegalReference   23705 non-null  object
 7   SoldAsVacant     23705 non-null  object
 8   OwnerName        23705 non-null  object
 9   OwnerAddress     23705 non-null  object
 10  Acreage          23705 non-null  float64
 11  TaxDistrict      23705 non-null  object
 12  LandValue        23705 non-null  object
 13  BuildingValue    23705 non-null  object
 14  TotalValue       23705 non-null  object
 15  YearBuilt        23705 non-null  int64
 16  Bedrooms         23705 non-null  int64
 17  FullBath         23705 non-null  int64
 18  HalfBath         23705 non-null  int64
 19  Street           23705 non-null  object
 20  City             23705 non-null  object
 21  OwnerStreet      23705 non-null  object
 22  OwnerCity        23705 non-null  object
 23  State            23705 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(5), object(17)
memory usage: 4.5+ MB

In [26]:
df.head(2)

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,...,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,Street,City,OwnerStreet,OwnerCity,State
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,"$240,000.00",20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",...,"$235,700.00",1986,3,3,0,1808 FOX CHASE DR,GOODLETTSVILLE,1808 FOX CHASE DR,GOODLETTSVILLE,TN
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,"$366,000.00",20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",...,"$319,000.00",1998,3,3,2,1832 FOX CHASE DR,GOODLETTSVILLE,1832 FOX CHASE DR,GOODLETTSVILLE,TN

# Drop propertyAddress and OwnerAddress columns

In [27]:
df.drop(columns = ['PropertyAddress', 'OwnerAddress'], inplace = True)

In [28]:
df.head(2)

,UniqueID,ParcelID,LandUse,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,Acreage,TaxDistrict,...,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,Street,City,OwnerStreet,OwnerCity,State
0,2045,007 00 0 125.00,SINGLE FAMILY,2013-04-09,"$240,000.00",20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE",2.3,GENERAL SERVICES DISTRICT,...,"$235,700.00",1986,3,3,0,1808 FOX CHASE DR,GOODLETTSVILLE,1808 FOX CHASE DR,GOODLETTSVILLE,TN
1,16918,007 00 0 130.00,SINGLE FAMILY,2014-06-10,"$366,000.00",20140619-0053768,No,"BONER, CHARLES & LESLIE",3.5,GENERAL SERVICES DISTRICT,...,"$319,000.00",1998,3,3,2,1832 FOX CHASE DR,GOODLETTSVILLE,1832 FOX CHASE DR,GOODLETTSVILLE,TN

# Arrange table properly

In [29]:
df.head(2)

,UniqueID,ParcelID,LandUse,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,Acreage,TaxDistrict,...,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,Street,City,OwnerStreet,OwnerCity,State
0,2045,007 00 0 125.00,SINGLE FAMILY,2013-04-09,"$240,000.00",20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE",2.3,GENERAL SERVICES DISTRICT,...,"$235,700.00",1986,3,3,0,1808 FOX CHASE DR,GOODLETTSVILLE,1808 FOX CHASE DR,GOODLETTSVILLE,TN
1,16918,007 00 0 130.00,SINGLE FAMILY,2014-06-10,"$366,000.00",20140619-0053768,No,"BONER, CHARLES & LESLIE",3.5,GENERAL SERVICES DISTRICT,...,"$319,000.00",1998,3,3,2,1832 FOX CHASE DR,GOODLETTSVILLE,1832 FOX CHASE DR,GOODLETTSVILLE,TN

In [30]:
df = df[['ParcelID', 'LandUse', 'Street', 'City', 'SaleDate', 'SalePrice', 'LegalReference', 'SoldAsVacant', 'OwnerName', 'OwnerStreet', 'OwnerCity', 'State', 'Acreage', 'TaxDistrict', 'LandValue', 'BuildingValue', 'TotalValue', 'YearBuilt', 'Bedrooms', 'FullBath', 'HalfBath']]

In [31]:
df

,ParcelID,LandUse,Street,City,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerStreet,...,State,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,007 00 0 125.00,SINGLE FAMILY,1808 FOX CHASE DR,GOODLETTSVILLE,2013-04-09,"$240,000.00",20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE",1808 FOX CHASE DR,...,TN,2.30,GENERAL SERVICES DISTRICT,"$240,000.00","$168,200.00","$235,700.00",1986,3,3,0
1,007 00 0 130.00,SINGLE FAMILY,1832 FOX CHASE DR,GOODLETTSVILLE,2014-06-10,"$366,000.00",20140619-0053768,No,"BONER, CHARLES & LESLIE",1832 FOX CHASE DR,...,TN,3.50,GENERAL SERVICES DISTRICT,"$366,000.00","$264,100.00","$319,000.00",1998,3,3,2
2,007 00 0 138.00,SINGLE FAMILY,1864 FOX CHASE DR,GOODLETTSVILLE,2016-09-26,"$435,000.00",20160927-0101718,No,"WILSON, JAMES E. & JOANNE",1864 FOX CHASE DR,...,TN,2.90,GENERAL SERVICES DISTRICT,"$435,000.00","$216,200.00","$298,000.00",1987,4,3,0
3,007 00 0 143.00,SINGLE FAMILY,1853 FOX CHASE DR,GOODLETTSVILLE,2016-01-29,"$255,000.00",20160129-0008913,No,"BAKER, JAY K. & SUSAN E.",1853 FOX CHASE DR,...,TN,2.60,GENERAL SERVICES DISTRICT,"$255,000.00","$147,300.00","$197,300.00",1985,3,3,0
4,007 00 0 149.00,SINGLE FAMILY,1829 FOX CHASE DR,GOODLETTSVILLE,2014-10-10,"$278,000.00",20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.",1829 FOX CHASE DR,...,TN,2.00,GENERAL SERVICES DISTRICT,"$278,000.00","$152,300.00","$202,300.00",1984,4,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54210,180 00 0 081.00,SINGLE FAMILY,6640 HOLT RD,NASHVILLE,2016-07-08,"$258,000.00",20160712-0071418,No,"CAHILL, DAVID W. II & MORYN",6640 HOLT RD,...,TN,3.00,GENERAL SERVICES DISTRICT,"$258,000.00","$155,800.00","$268,000.00",1978,4,2,0
54211,180 00 0 085.00,SINGLE FAMILY,6608 HOLT RD,NASHVILLE,2015-07-27,"$339,528.00",20150804-0077423,No,"MISRA, SANJEEV & YABKO, STACEY",6608 HOLT RD,...,TN,3.00,GENERAL SERVICES DISTRICT,"$339,528.00","$141,700.00","$252,700.00",1978,3,2,0
54212,180 00 0 094.00,SINGLE FAMILY,6635 HOLT RD,NASHVILLE,2014-09-05,"$230,000.00",20140905-0081621,No,"RALSTON, MARY DEE, IRREVOCABLE TRUST",6635 HOLT RD,...,TN,3.03,GENERAL SERVICES DISTRICT,"$230,000.00","$210,400.00","$321,900.00",1980,3,2,0
54213,180 00 0 114.00,SINGLE FAMILY,6552 REDMOND LN,NASHVILLE,2014-11-24,"$237,900.00",20141125-0108837,No,"MARTIN, KARA F. & SETH",6552 REDMOND LN,...,TN,1.03,GENERAL SERVICES DISTRICT,"$237,900.00","$104,100.00","$163,100.00",1985,3,3,0
54214,180 00 0 230.00,SINGLE FAMILY,105 HOLT HILLS RD,NASHVILLE,2014-11-12,"$259,000.00",20141203-0110910,No,"AKERS, DOUGLAS P. & MELISSA W.",105 HOLT HILLS RD,...,TN,0.46,GENERAL SERVICES DISTRICT,"$259,000.00","$194,000.00","$253,000.00",2001,3,2,1

In [34]:
pd.set_option('display.max_columns', 21)

In [35]:
df

,ParcelID,LandUse,Street,City,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerStreet,OwnerCity,State,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,007 00 0 125.00,SINGLE FAMILY,1808 FOX CHASE DR,GOODLETTSVILLE,2013-04-09,"$240,000.00",20130412-0036474,No,"FRAZIER, CYRENTHA...",1808 FOX CHASE DR,GOODLETTSVILLE,TN,2.30,GENERAL SERVICES ...,"$240,000.00","$168,200.00","$235,700.00",1986,3,3,0
1,007 00 0 130.00,SINGLE FAMILY,1832 FOX CHASE DR,GOODLETTSVILLE,2014-06-10,"$366,000.00",20140619-0053768,No,"BONER, CHARLES & ...",1832 FOX CHASE DR,GOODLETTSVILLE,TN,3.50,GENERAL SERVICES ...,"$366,000.00","$264,100.00","$319,000.00",1998,3,3,2
2,007 00 0 138.00,SINGLE FAMILY,1864 FOX CHASE DR,GOODLETTSVILLE,2016-09-26,"$435,000.00",20160927-0101718,No,"WILSON, JAMES E. ...",1864 FOX CHASE DR,GOODLETTSVILLE,TN,2.90,GENERAL SERVICES ...,"$435,000.00","$216,200.00","$298,000.00",1987,4,3,0
3,007 00 0 143.00,SINGLE FAMILY,1853 FOX CHASE DR,GOODLETTSVILLE,2016-01-29,"$255,000.00",20160129-0008913,No,"BAKER, JAY K. & S...",1853 FOX CHASE DR,GOODLETTSVILLE,TN,2.60,GENERAL SERVICES ...,"$255,000.00","$147,300.00","$197,300.00",1985,3,3,0
4,007 00 0 149.00,SINGLE FAMILY,1829 FOX CHASE DR,GOODLETTSVILLE,2014-10-10,"$278,000.00",20141015-0095255,No,"POST, CHRISTOPHER...",1829 FOX CHASE DR,GOODLETTSVILLE,TN,2.00,GENERAL SERVICES ...,"$278,000.00","$152,300.00","$202,300.00",1984,4,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54210,180 00 0 081.00,SINGLE FAMILY,6640 HOLT RD,NASHVILLE,2016-07-08,"$258,000.00",20160712-0071418,No,"CAHILL, DAVID W. ...",6640 HOLT RD,NASHVILLE,TN,3.00,GENERAL SERVICES ...,"$258,000.00","$155,800.00","$268,000.00",1978,4,2,0
54211,180 00 0 085.00,SINGLE FAMILY,6608 HOLT RD,NASHVILLE,2015-07-27,"$339,528.00",20150804-0077423,No,"MISRA, SANJEEV & ...",6608 HOLT RD,NASHVILLE,TN,3.00,GENERAL SERVICES ...,"$339,528.00","$141,700.00","$252,700.00",1978,3,2,0
54212,180 00 0 094.00,SINGLE FAMILY,6635 HOLT RD,NASHVILLE,2014-09-05,"$230,000.00",20140905-0081621,No,"RALSTON, MARY DEE...",6635 HOLT RD,NASHVILLE,TN,3.03,GENERAL SERVICES ...,"$230,000.00","$210,400.00","$321,900.00",1980,3,2,0
54213,180 00 0 114.00,SINGLE FAMILY,6552 REDMOND LN,NASHVILLE,2014-11-24,"$237,900.00",20141125-0108837,No,"MARTIN, KARA F. &...",6552 REDMOND LN,NASHVILLE,TN,1.03,GENERAL SERVICES ...,"$237,900.00","$104,100.00","$163,100.00",1985,3,3,0
54214,180 00 0 230.00,SINGLE FAMILY,105 HOLT HILLS RD,NASHVILLE,2014-11-12,"$259,000.00",20141203-0110910,No,"AKERS, DOUGLAS P....",105 HOLT HILLS RD,NASHVILLE,TN,0.46,GENERAL SERVICES ...,"$259,000.00","$194,000.00","$253,000.00",2001,3,2,1

In [36]:
df.head(50)

,ParcelID,LandUse,Street,City,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerStreet,OwnerCity,State,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,007 00 0 125.00,SINGLE FAMILY,1808 FOX CHASE DR,GOODLETTSVILLE,2013-04-09,"$240,000.00",20130412-0036474,No,"FRAZIER, CYRENTHA...",1808 FOX CHASE DR,GOODLETTSVILLE,TN,2.30,GENERAL SERVICES ...,"$240,000.00","$168,200.00","$235,700.00",1986,3,3,0
1,007 00 0 130.00,SINGLE FAMILY,1832 FOX CHASE DR,GOODLETTSVILLE,2014-06-10,"$366,000.00",20140619-0053768,No,"BONER, CHARLES & ...",1832 FOX CHASE DR,GOODLETTSVILLE,TN,3.50,GENERAL SERVICES ...,"$366,000.00","$264,100.00","$319,000.00",1998,3,3,2
2,007 00 0 138.00,SINGLE FAMILY,1864 FOX CHASE DR,GOODLETTSVILLE,2016-09-26,"$435,000.00",20160927-0101718,No,"WILSON, JAMES E. ...",1864 FOX CHASE DR,GOODLETTSVILLE,TN,2.90,GENERAL SERVICES ...,"$435,000.00","$216,200.00","$298,000.00",1987,4,3,0
3,007 00 0 143.00,SINGLE FAMILY,1853 FOX CHASE DR,GOODLETTSVILLE,2016-01-29,"$255,000.00",20160129-0008913,No,"BAKER, JAY K. & S...",1853 FOX CHASE DR,GOODLETTSVILLE,TN,2.60,GENERAL SERVICES ...,"$255,000.00","$147,300.00","$197,300.00",1985,3,3,0
4,007 00 0 149.00,SINGLE FAMILY,1829 FOX CHASE DR,GOODLETTSVILLE,2014-10-10,"$278,000.00",20141015-0095255,No,"POST, CHRISTOPHER...",1829 FOX CHASE DR,GOODLETTSVILLE,TN,2.00,GENERAL SERVICES ...,"$278,000.00","$152,300.00","$202,300.00",1984,4,3,0
5,007 00 0 151.00,SINGLE FAMILY,1821 FOX CHASE DR,GOODLETTSVILLE,2014-07-16,"$267,000.00",20140718-0063802,No,"FIELDS, KAREN L. ...",1821 FOX CHASE DR,GOODLETTSVILLE,TN,2.00,GENERAL SERVICES ...,"$267,000.00","$190,400.00","$259,800.00",1980,3,3,0
6,007 14 0 002.00,SINGLE FAMILY,2005 SADIE LN,GOODLETTSVILLE,2014-08-28,"$171,000.00",20140903-0080214,No,"HINTON, MICHAEL R...",2005 SADIE LN,GOODLETTSVILLE,TN,1.03,GENERAL SERVICES ...,"$171,000.00","$137,900.00","$177,900.00",1976,3,2,0
7,007 14 0 024.00,SINGLE FAMILY,1917 GRACELAND DR,GOODLETTSVILLE,2016-09-27,"$262,000.00",20161005-0105441,No,"BAILOR, DARRELL &...",1917 GRACELAND DR,GOODLETTSVILLE,TN,1.03,GENERAL SERVICES ...,"$262,000.00","$157,900.00","$197,900.00",1978,3,2,0
8,007 14 0 026.00,SINGLE FAMILY,1428 SPRINGFIELD...,GOODLETTSVILLE,2015-08-14,"$285,000.00",20150819-0083440,No,"ROBERTS, MISTY L....",1428 SPRINGFIELD...,GOODLETTSVILLE,TN,1.67,GENERAL SERVICES ...,"$285,000.00","$176,900.00","$222,300.00",2000,3,2,1
9,007 14 0 034.00,SINGLE FAMILY,1420 SPRINGFIELD...,GOODLETTSVILLE,2014-08-29,"$340,000.00",20140909-0082348,No,"LEE, JEFFREY & NANCY",1420 SPRINGFIELD...,GOODLETTSVILLE,TN,1.30,GENERAL SERVICES ...,"$340,000.00","$179,600.00","$219,600.00",1995,5,3,0
13,007 15 0 002.00,SINGLE FAMILY,629 GAYLEMORE DR,GOODLETTSVILLE,2013-06-07,"$189,900.00",20130612-0059715,No,"URRUTIA, CARLOS M...",629 GAYLEMORE DR,GOODLETTSVILLE,TN,1.07,GENERAL SERVICES ...,"$189,900.00","$203,600.00","$243,600.00",2006,4,4,0
14,007 15 0 003.00,SINGLE FAMILY,633 GAYLEMORE DR,GOODLETTSVILLE,2014-06-30,"$157,500.00",20140702-0058050,No,"SALDANA, ALMA J. ...",633 GAYLEMORE DR,GOODLETTSVILLE,TN,1.03,GENERAL SERVICES ...,"$157,500.00","$115,400.00","$155,400.00",1974,4,2,0
15,007 15 0 004.00,SINGLE FAMILY,637 GAYLEMORE DR,GOODLETTSVILLE,2014-06-30,"$247,400.00",20140630-0057267,No,"MCKINNEY, ROBERT ...",637 GAYLEMORE DR,GOODLETTSVILLE,TN,1.03,GENERAL SERVICES ...,"$247,400.00","$180,300.00","$234,000.00",1974,3,3,0
16,007 15 0 008.00,SINGLE FAMILY,1976 SADIE LN,GOODLETTSVILLE,2016-07-15,"$211,500.00",20160720-0074793,No,"MILLER, JAMES L. ...",2001 SADIE LN,GOODLETTSVILLE,TN,1.08,GENERAL SERVICES ...,"$211,500.00","$129,200.00","$169,200.00",1974,4,2,0
17,007 15 0 014.00,SINGLE FAMILY,644 GAYLEMORE DR,GOODLETTSVILLE,2015-03-31,"$185,900.00",20150402-0029022,No,"SANDAGE, LEAH S.",644 GAYLEMORE DR,GOODLETTSVILLE,TN,1.03,GENERAL SERVICES ...,"$185,900.00","$127,400.00","$167,400.00",1974,3,2,0
18,007 15 0 020.00,SINGLE FAMILY,1921 NORMERLE DR,GOODLETTSVILLE,2013-10-11,"$349,900.00",20131018-0109102,No,"VAUGHN, JOHN",1921 NORMERLE DR,GOODLETTSVILLE,TN,1.03,GENERAL SERVICES ...,"$349,900.00","$286,500.00","$346,300.00",1974,3,3,1
19,007 15 0 031.00,SINGLE FAMILY,1916 NORMERLE DR,GOODLETTSVILLE,2013-06-28,"$192,500.00",20130711-0071698,No,"PARKS, KRISTEN LE...",1916 NORMERLE DR,GOODLETTSVILLE,TN,1.00,GENERAL SERVICES ...,"$192,500.00","$130,400.00","$170,400.00",1986,3,2,1
20,007 15 0 044.00,SINGLE FAMILY,2050 GRACELAND DR,GOODLETTSVILLE,2015-02-10,"$279,900.00",20150212-0012993,No,"ANGELL, MARGO G. ...",2050 GRACELAND DR,GOODLETTSVILLE,TN,1.28,GENERAL SERVICES ...,"$279,900.00","$238,900.00","$278,900.00",1985,3,3,0
21,007 15 0 048.00,SINGLE FAMILY,2034 GRACELAND DR,GOODLETTSVILLE,2016-04-14,"$379,900.00",20160418-0036715,No,"DOSS, GLEN KEVIN ...",2034 GRACELAND DR,GOODLETTSVILLE,TN,2.61,GENERAL SERVICES ...,"$379,900.00","$330,700.00","$383,600.00",1997,5,4,1
22,007 15 0 052.00,SINGLE FAMILY,811 BENTON CT,GOODLETTSVILLE,2013-07-08,"$192,500.00",20130712-0072376,No,"BRAKE, MICHAEL E....",811 BENTON CT,GOODLETTSVILLE,TN,1.10,GENERAL SERVICES ...,"$192,500.00","$158,000.00","$198,000.00",1989,3,3,0
23,010 00 0 045.00,SINGLE FAMILY,331 VIEW RIDGE DR,GOODLETTSVILLE,2015-08-31,"$193,500.00",20150903-0090036,No,"BENJAMIN, DAVID A...",331 VIEW RIDGE DR,GOODLETTSVILLE,TN,1.69,GENERAL SERVICES ...,"$193,500.00","$116,600.00","$151,700.00",1988,3,2,0
24,010 00 0 052.00,SINGLE FAMILY,361 VIEW RIDGE DR,GOODLETTSVILLE,2013-10-21,"$172,400.00",20131030-0112723,No,"WILLIAMS, JOSEPH ...",361 VIEW RIDGE DR,GOODLETTSVILLE,TN,2.50,GENERAL SERVICES ...,"$172,400.00","$112,800.00","$152,600.00",1982,3,2,0
26,012 00 0 082.00,SINGLE FAMILY,8154 OLD SPRINGF...,GOODLETTSVILLE,2015-01-26,"$162,500.00",20150127-0007529,No,"SMITH, JAMES M., JR.",8154 OLD SPRINGF...,GOODLETTSVILLE,TN,2.31,GENERAL SERVICES ...,"$162,500.00","$119,300.00","$179,200.00",1986,2,1,1
27,012 00 0 083.00,SINGLE FAMILY,8158 OLD SPRINGF...,GOODLETTSVILLE,2014-08-01,"$235,000.00",20140808-0071505,No,"HOWARD, MARK & LU...",8158 OLD SPRINGF...,GOODLETTSVILLE,TN,2.31,GENERAL SERVICES ...,"$235,000.00","$134,800.00","$232,300.00",1983,3,2,0
28,012 00 0 109.00,SINGLE FAMILY,8136 OLD SPRINGF...,GOODLETTSVILLE,2013-10-11,"$225,000.00",20131022-0110073,No,"DAWSON, KENNETH D...",8136 OLD SPRINGF...,GOODLETTSVILLE,TN,3.71,GENERAL SERVICES ...,"$225,000.00","$140,300.00","$207,100.00",1987,3,2,0
29,012 02 0 011.00,SINGLE FAMILY,1334 SPRINGFIELD...,GOODLETTSVILLE,2015-08-27,"$271,000.00",20150901-0088477,No,"NAUERT, MARK II &...",1334 SPRINGFIELD...,GOODLETTSVILLE,TN,1.75,GENERAL SERVICES ...,"$271,000.00","$153,700.00","$220,900.00",1979,3,3,0
30,012 02 0 019.00,SINGLE FAMILY,1412 SPRINGFIELD...,GOODLETTSVILLE,2014-03-18,"$359,900.00",20140321-0023358,No,"BATSON, JEFFERY L.",1412 SPRINGFIELD...,GOODLETTSVILLE,TN,1.17,GENERAL SERVICES ...,"$359,900.00","$333,300.00","$373,300.00",2000,4,4,1
31,012 03 0 006.00,SINGLE FAMILY,612 GAYLEMORE DR,GOODLETTSVILLE,2016-03-11,"$276,500.00",20160317-0025384,No,"ADAMS, ALEXANDER ...",612 GAYLEMORE DR,GOODLETTSVILLE,TN,1.01,GENERAL SERVICES ...,"$276,500.00","$169,200.00","$209,200.00",1973,3,3,0
32,012 03 0 009.00,SINGLE FAMILY,2013 SUNNYSLOPE LN,GOODLETTSVILLE,2016-08-29,"$271,500.00",20160831-0091434,No,"ARNOLD, RACHEL & ...",2013 SUNNYSLOPE LN,GOODLETTSVILLE,TN,1.03,GENERAL SERVICES ...,"$271,500.00","$133,300.00","$173,300.00",1974,3,2,0
33,012 03 0 012.00,SINGLE FAMILY,600 SUNNYSLOPE CT,GOODLETTSVILLE,2014-05-14,"$205,900.00",20140529-0045974,No,"SKAGGS, BROCK A. ...",600 SUNNYSLOPE CT,GOODLETTSVILLE,TN,1.07,GENERAL SERVICES ...,"$205,900.00","$148,200.00","$188,200.00",1973,3,3,0
34,012 03 0 013.00,SINGLE FAMILY,604 SUNNYSLOPE CT,GOODLETTSVILLE,2016-09-23,"$228,000.00",20160927-0101636,No,"RED THUNDER, LLC",604 SUNNYSLOPE CT,GOODLETTSVILLE,TN,1.01,GENERAL SERVICES ...,"$228,000.00","$143,300.00","$183,300.00",1973,3,2,0
35,012 03 0 018.00,SINGLE FAMILY,609 SUNNYSLOPE CT,GOODLETTSVILLE,2013-03-15,"$160,000.00",20130319-0026986,No,"O'CONNELL, JAMES ...",609 SUNNYSLOPE CT,GOODLETTSVILLE,TN,1.07,GENERAL SERVICES ...,"$160,000.00","$104,900.00","$153,400.00",1973,3,3,0
36,012 03 0 023.00,SINGLE FAMILY,621 GAYLEMORE DR,GOODLETTSVILLE,2013-02-08,"$129,900.00",20130215-0015687,No,"TUDERS, KEVIN",621 GAYLEMORE DR,GOODLETTSVILLE,TN,1.05,GENERAL SERVICES ...,"$129,900.00","$138,900.00","$205,600.00",1974,3,1,1
37,012 03 0 025.00,SINGLE FAMILY,613 GAYLEMORE DR,GOODLETTSVILLE,2015-07-17,"$230,000.00",20150721-0071254,No,"BOISE, LINDSEY J....",613 GAYLEMORE DR,GOODLETTSVILLE,TN,0.98,GENERAL SERVICES ...,"$230,000.00","$126,400.00","$181,100.00",1974,3,2,0
38,015 14 0 011.00,SINGLE FAMILY,3128 UNION HILL RD,JOELTON,2015-10-01,"$90,000.00",20151006-0101964,No,"IBARRA-ROMERO, GR...",3128 UNION HILL RD,JOELTON,TN,0.93,GENERAL SERVICES ...,"$90,000.00","$64,100.00","$95,700.00",1964,3,1,0
39,015 14 0 045.00,SINGLE FAMILY,7515 GARY RD,JOELTON,2016-05-27,"$160,000.00",20160606-0056507,No,"PORTER, BRIAN KELLY",7515 GARY RD,JOELTON,TN,1.06,GENERAL SERVICES ...,"$160,000.00","$148,700.00","$180,000.00",1967,3,2,0
40,015 14 0 053.00,SINGLE FAMILY,7620 GERALD DR,JOELTON,2016-08-08,"$195,900.00",20160810-0083381,No,"TEMPLE, LORENE",7620 GERALD DR,JOELTON,TN,1.07,GENERAL SERVICES ...,"$195,900.00","$94,600.00","$150,500.00",1973,3,1,0
41,015 14 0 054.00,SINGLE FAMILY,7624 GERALD DR,JOELTON,2015-10-09,"$122,431.00",20151013-0103951,No,"STEWART, DONNA D.",7624 GERALD DR,JOELTON,TN,1.07,GENERAL SERVICES ...,"$122,431.00","$97,100.00","$140,700.00",1972,3,1,0
42,015 14 0 055.00,SINGLE FAMILY,7628 GERALD DR,JOELTON,2013-07-12,"$119,900.00",20130718-0074201,No,"PROULX, JENNIFER ...",7628 GERALD DR,JOELTON,TN,1.05,GENERAL SERVICES ...,"$119,900.00","$88,600.00","$119,300.00",1973,3,1,0
43,015 14 0 060.00,SINGLE FAMILY,3113 MILLIKEN DR,JOELTON,2013-08-20,"$145,000.00",20130821-0088382,No,"SMITH, HOLLI NICHOLE",3113 MILLIKEN DR,JOELTON,TN,0.98,GENERAL SERVICES ...,"$145,000.00","$111,200.00","$141,200.00",1996,3,2,0
44,015 14 0 060.00,SINGLE FAMILY,3113 MILLIKEN DR,JOELTON,2016-01-15,"$160,000.00",20160119-0004923,No,"SMITH, HOLLI NICHOLE",3113 MILLIKEN DR,JOELTON,TN,0.98,GENERAL SERVICES ...,"$160,000.00","$111,200.00","$141,200.00",1996,3,2,0
45,015 14 0 061.00,SINGLE FAMILY,3117 MILLIKEN DR,JOELTON,2016-03-18,"$169,900.00",20160413-0035454,No,"DISMANG, JEREMY",3117 MILLIKEN DR,JOELTON,TN,0.98,GENERAL SERVICES ...,"$169,900.00","$115,900.00","$145,900.00",1997,3,2,0
46,015 14 0 071.00,SINGLE FAMILY,3107 MARGIE DR,JOELTON,2013-05-10,"$103,500.00",20130513-0047997,No,"DOWNS, JESSICA",3107 MARGIE DR,JOELTON,TN,1.03,GENERAL SERVICES ...,"$103,500.00","$83,000.00","$113,000.00",1972,3,1,0
47,015 14 0 075.00,SINGLE FAMILY,3124 MARGIE DR,JOELTON,2015-07-31,"$184,000.00",20150803-0076727,No,"MURRY, SHAWN",3124 MARGIE DR,JOELTON,TN,1.03,GENERAL SERVICES ...,"$184,000.00","$116,100.00","$146,100.00",1972,4,2,0
48,016 00 0 093.00,SINGLE FAMILY,2466 UNION HILL RD,GOODLETTSVILLE,2015-10-13,"$165,000.00",20151014-0104536,No,"HARRISON, JASON C...",2466 UNION HILL RD,GOODLETTSVILLE,TN,2.00,GENERAL SERVICES ...,"$165,000.00","$134,300.00","$174,100.00",1976,3,2,0
49,016 00 0 110.00,SINGLE FAMILY,7221 APPLE VIEW DR,GOODLETTSVILLE,2014-09-24,"$290,000.00",20141009-0093665,No,"MILLER, WILLIAM B...",7221 APPLE VIEW DR,GOODLETTSVILLE,TN,1.35,GENERAL SERVICES ...,"$290,000.00","$173,300.00","$240,100.00",1993,3,2,0
50,016 00 0 143.00,SINGLE FAMILY,7104 LAMA TERRA DR,GOODLETTSVILLE,2015-07-06,"$260,000.00",20150708-0066261,No,"GIGEAR, DAVID & D...",7104 LAMA TERRA DR,GOODLETTSVILLE,TN,1.14,GENERAL SERVICES ...,"$260,000.00","$147,700.00","$196,200.00",1985,3,2,0
51,016 00 0 184.00,SINGLE FAMILY,7143 LAMA TERRA DR,GOODLETTSVILLE,2015-10-09,"$200,000.00",20151013-0103879,No,"MORELOCK, WALTER ...",7143 LAMA TERRA DR,GOODLETTSVILLE,TN,1.46,GENERAL SERVICES ...,"$200,000.00","$134,500.00","$169,600.00",1993,3,3,0
52,016 00 0 191.00,SINGLE FAMILY,7175 LAMA TERRA DR,GOODLETTSVILLE,2013-07-29,"$165,000.00",20130729-0078604,No,"WALL, COREY D. & ...",7175 LAMA TERRA DR,GOODLETTSVILLE,TN,1.77,GENERAL SERVICES ...,"$165,000.00","$121,400.00","$156,500.00",1988,3,3,0
53,016 00 0 216.00,SINGLE FAMILY,6912 RIDGERUNNER CT,GOODLETTSVILLE,2015-07-10,"$230,000.00",20150713-0067794,No,"SHRUM, AMANDA & H...",6912 RIDGERUNNER CT,GOODLETTSVILLE,TN,0.94,GENERAL SERVICES ...,"$230,000.00","$144,500.00","$179,600.00",1989,3,2,1

# Export to csv

In [40]:
df.to_csv(r"C:\Users\a\Downloads\NashvilleUpdated.csv", index = False)